// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsPOLyFsFoKf7OUkLr-N6Ya_g6LiyQGjQ',
    appId: '1:1093855992848:web:5ad5cb1905b58a07affe95',
    messagingSenderId: '1093855992848',
    projectId: 'pricepulse-e7f39',
    authDomain: 'pricepulse-e7f39.firebaseapp.com',
    storageBucket: 'pricepulse-e7f39.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLLF_Y6d7AzRiEcUcSa-HEjYb7020JeiI',
    appId: '1:1093855992848:android:0e4d19d889f07068affe95',
    messagingSenderId: '1093855992848',
    projectId: 'pricepulse-e7f39',
    storageBucket: 'pricepulse-e7f39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ4vhbnFr9pD78-OTPihB0PjLYWOdJqOE',
    appId: '1:1093855992848:ios:f97f710e6ad204f5affe95',
    messagingSenderId: '1093855992848',
    projectId: 'pricepulse-e7f39',
    storageBucket: 'pricepulse-e7f39.firebasestorage.app',
    iosBundleId: 'com.example.pricePulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ4vhbnFr9pD78-OTPihB0PjLYWOdJqOE',
    appId: '1:1093855992848:ios:f97f710e6ad204f5affe95',
    messagingSenderId: '1093855992848',
    projectId: 'pricepulse-e7f39',
    storageBucket: 'pricepulse-e7f39.firebasestorage.app',
    iosBundleId: 'com.example.pricePulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsPOLyFsFoKf7OUkLr-N6Ya_g6LiyQGjQ',
    appId: '1:1093855992848:web:d5da6ec24f94e6b2affe95',
    messagingSenderId: '1093855992848',
    projectId: 'pricepulse-e7f39',
    authDomain: 'pricepulse-e7f39.firebaseapp.com',
    storageBucket: 'pricepulse-e7f39.firebasestorage.app',
  );
}
